In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [97]:
df = pd.read_csv('./Weather_Data.csv')
df.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes

In [98]:
df.replace(['No', 'Yes'], [0, 1], inplace=True)
df.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,1,1
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,1,1
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,1,1
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,1,1
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,1,1

In [99]:
print(df.dtypes)

Date              object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed      int64
WindDir9am        object
WindDir3pm        object
WindSpeed9am       int64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday          int64
RainTomorrow       int64
dtype: object

In [100]:
# CLEARLY, WindDir9am, WindDir3pm and WindGustDir are 3 categorical values that need to be converted by one hot encoding
df = pd.get_dummies(df, columns=['WindGustDir', 'WindDir9am', 'WindDir3pm'])
df.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,41,17,20,92,...,False,False,False,False,False,True,False,False,False,False
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,41,9,13,83,...,False,False,False,False,False,False,False,False,False,False
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,41,17,2,88,...,False,False,False,False,False,False,False,False,False,False
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,41,22,20,83,...,False,False,False,False,False,False,False,False,False,False
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,41,11,6,88,...,False,False,False,False,False,False,False,True,False,False

In [101]:
df.drop('Date', axis=1, inplace=True)

In [102]:
df = df.astype('float64')
df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,19.5,22.4,15.6,6.2,0.0,41.0,17.0,20.0,92.0,84.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,19.5,25.6,6.0,3.4,2.7,41.0,9.0,13.0,83.0,73.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21.6,24.5,6.6,2.4,0.1,41.0,17.0,2.0,88.0,86.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20.2,22.8,18.8,2.2,0.0,41.0,22.0,20.0,83.0,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,19.7,25.7,77.4,4.8,0.0,41.0,11.0,6.0,88.0,74.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [103]:
columns = df.columns
len(columns)

66

In [104]:
x = df[[column for column in columns if column != 'RainTomorrow']]
x.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,19.5,22.4,15.6,6.2,0.0,41.0,17.0,20.0,92.0,84.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,19.5,25.6,6.0,3.4,2.7,41.0,9.0,13.0,83.0,73.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21.6,24.5,6.6,2.4,0.1,41.0,17.0,2.0,88.0,86.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20.2,22.8,18.8,2.2,0.0,41.0,22.0,20.0,83.0,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,19.7,25.7,77.4,4.8,0.0,41.0,11.0,6.0,88.0,74.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [105]:
y = df['RainTomorrow']
y.head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: RainTomorrow, dtype: float64

In [106]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)
predictions = []

In [107]:
# LINEAR REGRESSION CODE

from sklearn.linear_model import LinearRegression

lin_reg_model = LinearRegression()
lin_reg_model.fit(x_train, y_train)
lin_reg_pred = lin_reg_model.predict(x_test)
predictions.append(lin_reg_pred)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, lin_reg_pred)
mae = mean_absolute_error(y_test, lin_reg_pred)
r2 = r2_score(y_test, lin_reg_pred)

results = pd.DataFrame({
    'Metrics': ['Mean Squared Error', 'Mean Absolute Error', 'R2 Score'],
    'Values': [mse, mae, r2],
})
print(results)

               Metrics    Values
0   Mean Squared Error  0.115721
1  Mean Absolute Error  0.256318
2             R2 Score  0.427132

In [108]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=4)
knn_model.fit(x_train, y_train)
knn_pred = knn_model.predict(x_test)
predictions.append(knn_pred)

from sklearn.metrics import accuracy_score, jaccard_score, f1_score
acc = accuracy_score(y_test, knn_pred)
jacc = jaccard_score(y_test, knn_pred)
f1 = f1_score(y_test, knn_pred)
knn_results = pd.DataFrame({
    'Metrics': ['Accuracy', 'Jaccard Score', 'F1 Score'],
    'Values': [acc, jacc, f1],
})
print(knn_results)

         Metrics    Values
0       Accuracy  0.818321
1  Jaccard Score  0.425121
2       F1 Score  0.596610

In [109]:
from sklearn.tree import DecisionTreeClassifier

dtc_model = DecisionTreeClassifier(max_depth=4)
dtc_model.fit(x_train, y_train)
dtc_pred = dtc_model.predict(x_test)
predictions.append(dtc_pred)

tree_acc = accuracy_score(y_test, dtc_pred)
tree_jacc = jaccard_score(y_test, dtc_pred)
tree_f1 = f1_score(y_test, dtc_pred)
dtc_results = pd.DataFrame({
    'Metrics': ['Accuracy', 'Jaccard Score', 'F1 Score'],
    'Values': [tree_acc, tree_jacc, tree_f1],
})
print(dtc_results)

         Metrics    Values
0       Accuracy  0.819847
1  Jaccard Score  0.470852
2       F1 Score  0.640244

In [110]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

logreg_model = LogisticRegression(solver='liblinear')
logreg_model.fit(x_train, y_train)
logreg_pred = logreg_model.predict(x_test)
predictions.append(logreg_pred)
logreg_predict_proba = logreg_model.predict_proba(x_test)
predictions_proba = []
predictions_proba.append(logreg_predict_proba)

accuracy = accuracy_score(y_test, logreg_pred)
jacc = jaccard_score(y_test, logreg_pred)
f1 = f1_score(y_test, logreg_pred)
logreg_log_loss = log_loss(y_test, logreg_predict_proba)

log_reg_results = pd.DataFrame({
    'Metrics': ['Accuracy', 'Jaccard Score', 'F1 Score', 'Log Loss'],
    'Values': [accuracy, jacc, f1, logreg_log_loss]
})
print(log_reg_results)

         Metrics    Values
0       Accuracy  0.836641
1  Jaccard Score  0.506912
2       F1 Score  0.672783
3       Log Loss  0.378902

In [113]:
from sklearn.svm import SVC

svm_model = SVC(kernel='poly', gamma='auto')
svm_model.fit(x_train, y_train)
svm_pred = svm_model.predict(x_test)
predictions.append(svm_pred)
svm_acc = accuracy_score(y_test, svm_pred)
svm_jacc = jaccard_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)
svm_results = pd.DataFrame({
    'Metrics': ['Accuracy', 'Jaccard Score', 'F1 Score'],
    'Values': [svm_acc, svm_jacc, svm_f1],
})
print(svm_results)

         Metrics    Values
0       Accuracy  0.822901
1  Jaccard Score  0.475113
2       F1 Score  0.644172

In [116]:
results['Model'] = 'Linear Regression'
knn_results['Model'] = 'KNN'
dtc_results['Model'] = 'Decision Tree'
log_reg_results['Model'] = 'Logistic Regression'
svm_results['Model'] = 'SVM'

results = results[['Model', 'Metrics', 'Values']]
knn_results = knn_results[['Model', 'Metrics', 'Values']]
dtc_results = dtc_results[['Model', 'Metrics', 'Values']]
log_reg_results = log_reg_results[['Model', 'Metrics', 'Values']]
svm_results = svm_results[['Model', 'Metrics', 'Values']]

report = pd.concat([results, knn_results, dtc_results, log_reg_results, svm_results], ignore_index=True)

print(report)

                  Model              Metrics    Values
0     Linear Regression   Mean Squared Error  0.115721
1     Linear Regression  Mean Absolute Error  0.256318
2     Linear Regression             R2 Score  0.427132
3                   KNN             Accuracy  0.818321
4                   KNN        Jaccard Score  0.425121
5                   KNN             F1 Score  0.596610
6         Decision Tree             Accuracy  0.819847
7         Decision Tree        Jaccard Score  0.470852
8         Decision Tree             F1 Score  0.640244
9   Logistic Regression             Accuracy  0.836641
10  Logistic Regression        Jaccard Score  0.506912
11  Logistic Regression             F1 Score  0.672783
12  Logistic Regression             Log Loss  0.378902
13                  SVM             Accuracy  0.822901
14                  SVM        Jaccard Score  0.475113
15                  SVM             F1 Score  0.644172